name: ox
recipe: drupal9
config:
  webroot: web
  php: '8.1'

proxy:
  appserver:
    - ox.lndo.site

  mercury:
    - mercury.lndo.site

  venus:
    - venus.lndo.site

  mars_web:
    - mars.lndo.site

services:

  ##
  # OX Site: The Management Dashboard: https://ox.lndo.site
  ##
  appserver:
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://ox.lndo.site"
    # xdebug: true

  # OX Client Site: Mercury
  ##
  mercury:
    type: php:8.0
    webroot: web
  mercury_db:
    type: mysql
    portforward: 33061

  ##
  # OX Client Site: Venus
  ##
  venus:
    type: php:8.0
    webroot: web
  venus_db:
    type: mysql
    portforward: 33062

  ##
  # OX Client Site: Mars
  ##
  mars:
    type: php:8.0
    webroot: web
  mars_db:
    type: mysql
    portforward: 33063
