# Schema for the configuration files of the Operations module.
operations.settings:
  type: config_object
  label: 'Operations settings'
  mapping:
    example:
      type: string
      label: 'Example'
