# Schema for the configuration files of the Site Manager module.
site_manager.settings:
  type: config_object
  label: 'Site Manager settings'
  mapping:
    example:
      type: string
      label: 'Example'
