# Schema for the configuration files of the Site module.
site.settings:
  type: config_object
  label: 'Site settings'
  mapping:
    state_factors:
      type: bool
      label: "The sources to use to determine site state."

site.site_definition.*:
  type: config_entity
  label: Site Definition
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string
