# Schema for the configuration files of the Site module.
site.settings:
  type: config_object
  label: 'Site settings'
  mapping:
    status_report_state:
      type: bool
      label: "Use the site's Status report to determine site state."

site.site_definition.*:
  type: config_entity
  label: Site Definition
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string
