# Schema for the configuration files of the Site Manager module.
site_manager.settings:
  type: config_object
  label: 'Site Manager settings'
  mapping:
    global_config_overrides:
      type: string
      label: 'Global Site Config Overrides'
      description: 'Enter YAML to load into all Site entities.'
